export const themeSetup = {
                token: {
                    // Brand
                    colorPrimary: '#494c51',
                    // Links
                    colorLink: '#60a5fa',
                    colorLinkHover: '#93c5fd',
                    // Text hierarchy
                    colorTextSecondary: '#cbd5e0',
                    colorTextTertiary: '#8c8c8c',
                    colorTextQuaternary: '#666666',
                    // Borders
                    colorBorder: '#4e545f',
                    colorBorderSecondary: '#3a3d42',
                    // Controls
                    controlHeight: 40,
                    borderRadius: 8,
                    borderRadiusLG: 12,
                },
                components: {
                    Button: {
                        primaryShadow: 'none',
                        defaultShadow: 'none',
                        dangerShadow: 'none',
                        // Default button dark theme
                        defaultBg: 'rgba(255, 255, 255, 0.04)',
                        defaultBorderColor: 'rgba(255, 255, 255, 0.15)',
                        defaultColor: 'rgba(255, 255, 255, 0.85)',
                        defaultHoverBg: 'rgba(255, 255, 255, 0.08)',
                        defaultHoverBorderColor: 'rgba(255, 255, 255, 0.3)',
                        defaultHoverColor: '#ffffff',
                        defaultActiveBg: 'rgba(255, 255, 255, 0.12)',
                        defaultActiveColor: '#ffffff',
                        defaultActiveBorderColor: 'rgba(255, 255, 255, 0.4)',
                        // Danger button dark theme
                        colorError: '#f87171',
                        colorErrorHover: '#fca5a5',
                        colorErrorBorderHover: '#fca5a5',
                        colorErrorActive: '#ef4444',
                    },
                    Input: {
                        colorBgContainer: 'rgba(255, 255, 255, 0.03)',
                        colorText: '#ffffff',
                        colorTextPlaceholder: '#666666',
                        activeShadow: 'none',
                    },
                    Select: {
                        colorBgContainer: 'rgba(255, 255, 255, 0.03)',
                        colorText: '#ffffff',
                        colorTextPlaceholder: '#666666',
                        // Dropdown
                        colorBgElevated: '#1e2128',
                        optionSelectedBg: 'rgba(96, 165, 250, 0.15)',
                        optionSelectedColor: '#ffffff',
                        optionActiveBg: 'rgba(255, 255, 255, 0.08)',
                        colorTextDisabled: 'rgba(255, 255, 255, 0.25)',
                    },
                    Segmented: {
                        itemColor: '#8c8c8c',
                        itemSelectedColor: '#ffffff',
                        itemSelectedBg: '#494c51',
                        trackBg: 'rgba(255, 255, 255, 0.05)',
                    },
                    Table: {
                        colorBgContainer: 'transparent',
                        headerBg: 'rgba(255, 255, 255, 0.04)',
                        headerColor: 'rgba(255, 255, 255, 0.5)',
                        borderColor: 'rgba(255, 255, 255, 0.08)',
                        rowHoverBg: 'rgba(255, 255, 255, 0.05)',
                        bodySortBg: 'transparent',
                        fixedHeaderSortActiveBg: '#1e2128',
                        colorText: 'rgba(255, 255, 255, 0.85)',
                    },
                    Modal: {
                        contentBg: 'rgba(22, 26, 34, 0.98)',
                        headerBg: 'transparent',
                        titleColor: 'rgba(255, 255, 255, 0.88)',
                        colorIcon: 'rgba(255, 255, 255, 0.45)',
                        colorIconHover: 'rgba(255, 255, 255, 0.88)',
                        footerBg: 'transparent',
                        titleFontSize: 18,
                    },
                    Drawer: {
                        colorBgElevated: 'rgba(22, 26, 34, 0.98)',
                        colorText: 'rgba(255, 255, 255, 0.88)',
                        colorIcon: 'rgba(255, 255, 255, 0.45)',
                        colorIconHover: 'rgba(255, 255, 255, 0.88)',
                        colorSplit: 'rgba(255, 255, 255, 0.1)',
                    },
                    DatePicker: {
                        colorBgContainer: 'rgba(255, 255, 255, 0.03)',
                        colorBgElevated: '#1e2128',
                        colorText: 'rgba(255, 255, 255, 0.88)',
                        colorTextPlaceholder: '#666666',
                        colorBorder: '#4e545f',
                        cellHoverBg: 'rgba(255, 255, 255, 0.08)',
                        colorPrimary: '#60a5fa',
                        colorPrimaryHover: '#93c5fd',
                        activeShadow: 'none',
                    },
                    Pagination: {
                        itemBg: 'rgba(255, 255, 255, 0.06)',
                        itemActiveBg: 'rgba(255, 255, 255, 0.08)',
                        itemLinkBg: 'transparent',
                        colorBorder: 'rgba(255, 255, 255, 0.12)',
                        colorText: 'rgba(255, 255, 255, 0.75)',
                        colorPrimary: '#60a5fa',
                        colorPrimaryHover: '#93c5fd',
                    },
                    InputNumber: {
                        colorBgContainer: 'rgba(255, 255, 255, 0.03)',
                        colorText: '#ffffff',
                        colorTextPlaceholder: '#666666',
                        activeShadow: 'none',
                    },
                    Form: {
                        labelColor: 'rgba(255, 255, 255, 0.65)',
                    },
                    Descriptions: {
                        labelBg: 'rgba(255, 255, 255, 0.04)',
                        contentColor: '#e2e8f0',
                        titleColor: 'rgba(255, 255, 255, 0.88)',
                        extraColor: '#e2e8f0',
                        colorTextSecondary: '#94a3b8',
                        colorSplit: 'rgba(255, 255, 255, 0.1)',
                    },
                    Statistic: {
                        colorText: 'rgba(255, 255, 255, 0.85)',
                        titleFontSize: 14,
                    },
                },
            };